name: land kernel builder

on: 
  push:
    branches:
      - test-10/main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: jprimero15/archlinux-docker:latest

    steps:
    - uses: actions/checkout@v2
    - name: Building land Kernel
      env:
        BOT_API_KEY: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }} 
      run: |
        chmod +x sync.sh
        chmod +x build-deps.sh
        bash build-deps.sh
        chmod +x print-vars.sh
        bash print-vars.sh
        chmod +x build.sh
        bash build.sh
        chmod +x upload.sh
        bash upload.sh
        
